name: Docker

on:
  workflow_dispatch:

  push:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image for testing
        run: docker build -t dockette/electron:16-slim-test -f 16/Dockerfile.slim .

      - name: Test Node.js
        run: docker run --rm dockette/electron:16-slim-test node --version

      - name: Test npm
        run: docker run --rm dockette/electron:16-slim-test npm --version

      - name: Test Electron build tools
        run: |
          docker run --rm dockette/electron:16-slim-test make --version
          docker run --rm dockette/electron:16-slim-test zip --version

  build:
    name: Build (dockette/electron:${{ matrix.tag }})
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./16/Dockerfile
            tag: "16"
          - dockerfile: ./16/Dockerfile.slim
            tag: "16-slim"

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: dockette/electron:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64

  docs:
    name: Docs
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dockette/electron
