name: Docker

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./16/Dockerfile
            tag: "16"
          - dockerfile: ./16/Dockerfile.slim
            tag: "16-slim"

      fail-fast: false

    name: Docker (dockette/electron:${{ matrix.tag }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: dockette/electron:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
